In [ ]:
import numpy as np
import scipy.linalg
import math
def row_echelon(M):
    """ Return Row Echelon Form of matrix A """
    A = np.copy(M)
    if (issubclass(A.dtype.type, np.integer)):
        A = A.astype(float)
    #A = M.astype(float)
    # if matrix A has no columns or rows,
    # it is already in REF, so we return itself
    r, c = A.shape
    if r == 0 or c == 0:
        return A

    # we search for non-zero element in the first column
    for i in range(len(A)):
        if A[i,0] != 0:
            break
    else:
        # if all elements in the first column is zero,
        # we perform REF on matrix from second column
        B = row_echelon(A[:,1:])
        # and then add the first zero-column back
        return np.hstack([A[:,:1], B])

    # if non-zero element happens not in the first row,
    # we switch rows
    if i > 0:
        ith_row = A[i].copy()
        A[i] = A[0]
        A[0] = ith_row

    # we divide first row by first element in it
    A[0] = A[0] / A[0,0]
    # we subtract all subsequent rows with first row (it has 1 now as first element)
    # multiplied by the corresponding element in the first column
    A[1:] -= A[0] * A[1:,0:1]

    # we perform REF on matrix from second row, from second column
    B = row_echelon(A[1:,1:])

    # we add first row and first (zero) column, and return
    return np.vstack([A[:1], np.hstack([A[1:,:1], B]) ])

# Primer Parcial 1C 2021


## EJ 1


In [ ]:
##ITEM A
A = np.array([[1,-1,0],[2,1,3],[1,0,1]])

In [ ]:
#im(A)
row_echelon(A.T)

array([[1.        , 2.        , 1.        ],
       [0.        , 1.        , 0.33333333],
       [0.        , 0.        , 0.        ]])

In [ ]:
row_echelon(A)

array([[ 1., -1.,  0.],
       [ 0.,  1.,  1.],
       [ 0.,  0.,  0.]])

In [ ]:
scipy.linalg.null_space(A)

array([[ 0.57735027],
       [ 0.57735027],
       [-0.57735027]])

In [ ]:
P = np.array([[1,-1,0],[0,1,1],[1,2,1],[0,3,1]])
row_echelon(P)

array([[ 1., -1.,  0.],
       [ 0.,  1.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

# Simulacro 1er Parcial 1C 2021


## EJ1


In [ ]:
Af = np.array([[0,-1,0,-1],[1,-1,1,0],[0,1,0,1],[0,1,0,1]])
row_echelon(Af.T)

array([[ 1.,  1., -1., -1.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [ ]:
M = np.array([[1,1,-1,-1, 1,-2,0,0],[0,1,0,0, -1,0,1,0],[-1,-1,0,1, 1,1,-1,-1],[-1,0,1,0, 0,1,0,0]])
M = row_echelon(M)
M[0] = M[0] - M[1]
M[0] = M[0] + M[2]
M[0] = M[0] + M[3]
M

array([[ 1.,  0.,  0.,  0., -2.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  0., -1.,  0.,  1.,  0.],
       [ 0.,  0.,  1., -0., -2.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  1., -2.,  1.,  1., -0.]])

In [ ]:
def g(x1,x2,x3,x4):
  return(np.array([-2*x1-x2-2*x3-2*x4, x3+x4, x1+x2+x3+x4, x1+x3]))

In [ ]:
print(g(1,1,-1,-1))
print(g(0,1,0,0))
print(g(-1,-1,0,1))
print(g(-1,0,1,0))

[ 1 -2  0  0]
[-1  0  1  0]
[ 1  1 -1 -1]
[0 1 0 0]


In [ ]:
Ag = M[:,4:]
NUAg = Ag.T
print(scipy.linalg.null_space(NUAg))
NUAg = np.c_[NUAg,np.zeros(4)]
row_echelon(NUAg)


[]


array([[ 1. ,  0.5,  1. ,  1. , -0. ],
       [ 0. ,  1. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. , -0. ]])

In [ ]:
print(np.linalg.matrix_rank(Ag))
row_echelon(Ag)

4


array([[ 1. , -0. , -0.5, -0.5],
       [ 0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. , -1. ],
       [ 0. ,  0. ,  0. ,  1. ]])

## EJ2


In [ ]:
a = 0
A = np.array([[1,-1,0,1],[-1,1,2,-4],[0,2,-1,3],[1,1,1,a]])
print(np.linalg.det(A[:2,:2]))
A

0.0


array([[ 1, -1,  0,  1],
       [-1,  1,  2, -4],
       [ 0,  2, -1,  3],
       [ 1,  1,  1,  0]])

In [ ]:
P = np.array([[1,0,0,0],[0,0,0,1],[0,0,1,0],[0,1,0,0]])
P

array([[1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0]])

In [ ]:
L = np.array([[1,0,0,0],[1,1,0,0],[0,1,1,0],[-1,0,-1,1]])
L

array([[ 1,  0,  0,  0],
       [ 1,  1,  0,  0],
       [ 0,  1,  1,  0],
       [-1,  0, -1,  1]])

In [ ]:
U = np.array([[1,-1,0,1],[0,2,1,a-1],[0,0,-2,4-a],[0,0,0,1-a]])
U

array([[ 1, -1,  0,  1],
       [ 0,  2,  1, -1],
       [ 0,  0, -2,  4],
       [ 0,  0,  0,  1]])

In [ ]:
print(P@A)

[[ 1 -1  0  1]
 [ 1  1  1  0]
 [ 0  2 -1  3]
 [-1  1  2 -4]]


In [ ]:
print(L@U)

[[ 1 -1  0  1]
 [ 1  1  1  0]
 [ 0  2 -1  3]
 [-1  1  2 -4]]


## EJ3

In [ ]:
def estado(A,v,k):
  for i in range(k):
    Av = A@v
    v = (Av) / np.linalg.norm(Av,2)
    r = (np.transpose(v)@A@v) / (np.transpose(v)@v)
    return(v,r)

In [ ]:
A= np.array([[-2,-3,3],[2,2,-2],[2,1,-1]])
np.linalg.eig(A)

(array([-2.00000000e+00, -7.21644966e-16,  1.00000000e+00]),
 array([[ 5.77350269e-01,  3.20493781e-16,  7.07106781e-01],
        [-5.77350269e-01, -7.07106781e-01,  0.00000000e+00],
        [-5.77350269e-01, -7.07106781e-01,  7.07106781e-01]]))

In [ ]:
v0 = np.array([1,2,3])

In [ ]:
print(A@v0)
print(np.linalg.norm(A@v0))
v1 = A@v0/np.linalg.norm(A@v0)

[1 0 1]
1.4142135623730951


In [ ]:
print(A@v1)
print(np.linalg.norm(A@v1,2))
v2 = A@v1 / np.linalg.norm(A@v1,2)

[0.70710678 0.         0.70710678]
0.9999999999999999


In [ ]:
estado(A,v0,10)

(array([0.70710678, 0.        , 0.70710678]), 1.0)

In [ ]:
v0.T@A@v0

4

In [ ]:
v0.T@v0

14

In [ ]:
v1.T@A@v1

0.9999999999999998

In [ ]:
v1.T@v1

0.9999999999999998

In [ ]:
estado(A,v0,0)

In [ ]:
(v0.T@A@v0)/(v0.T@v0)

0.2857142857142857

In [ ]:
A = np.array([[-2,0,0],[-1,5,-6],[-1,3,-4]])
print(np.linalg.eig(A)[0])
print(np.linalg.eig(A)[1])
v0 = np.array([1,4,3])

[-1.  2. -2.]
[[ 0.          0.          0.57735027]
 [-0.70710678 -0.89442719  0.57735027]
 [-0.70710678 -0.4472136   0.57735027]]


In [ ]:
print(estado(A,v0,1000))
print(estado(A,v0,2000))

(array([-0.81649658,  0.40824829, -0.40824829]), -0.666666666666667)
(array([-0.81649658,  0.40824829, -0.40824829]), -0.666666666666667)


# 1er Parcial 2022

## EJ1


In [ ]:
v1= np.array([1,1,1,1])
v2 = np.array([1,2,1,0])

u1= v1/np.linalg.norm(v1,2)
u2 = v2 - (np.dot(v2,u1)/(np.dot(u1,u1)))*u1
u2 = u2/ np.linalg.norm(u2,2)

In [ ]:
U = np.c_[u1,u2]
Af = U@np.linalg.inv(U.T@U)@U.T
Af

array([[ 0.25,  0.25,  0.25,  0.25],
       [ 0.25,  0.75,  0.25, -0.25],
       [ 0.25,  0.25,  0.25,  0.25],
       [ 0.25, -0.25,  0.25,  0.75]])

In [ ]:
Af@np.array([-1,0,1,0])

array([0, 0, 0, 0])

In [ ]:
Af@np.array([1,1,0,1])

array([-2,  0,  2,  2])

In [ ]:
Af@np.array([2,0,-2,0])

array([0, 0, 0, 0])

In [ ]:
Ah = np.array([[2,4,2,0],[-2,4,2,0],[0,0,0,4]])

In [ ]:
hof = Ah@Af
hof

array([[ 2.,  4.,  2.,  0.],
       [ 1.,  3.,  1., -1.],
       [ 1., -1.,  1.,  3.]])

In [ ]:
row_echelon(hof.T)

array([[ 1. ,  0.5,  0.5],
       [ 0. ,  1. , -3. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ]])

## EJ2


In [ ]:
n = 10**4
A = np.array([[1,10000,50000],[1,30000,30000],[1,10000,20000]])
L = np.array([[1,0,0],[1,1,0],[1,0,1]])
U = np.array([[1,10000,50000],[0,20000,-20000],[0,0,-30000]])
print(A)
print(L@U)
print(U)

[[    1 10000 50000]
 [    1 30000 30000]
 [    1 10000 20000]]
[[    1 10000 50000]
 [    1 30000 30000]
 [    1 10000 20000]]
[[     1  10000  50000]
 [     0  20000 -20000]
 [     0      0 -30000]]


In [ ]:
b = np.array([20000/3,20000/3,10000/3])
x_hat = np.array([0,0.1111,0.1111])
x= np.array([0,1/9,1/9])

In [ ]:
A@x

array([6666.66666667, 6666.66666667, 3333.33333333])

In [ ]:
A@x_hat

array([6666., 6666., 3333.])

In [ ]:
np.linalg.norm((x_hat - x),np.inf)/np.linalg.norm(x,np.inf)


9.999999999990572e-05

## EJ 3

In [ ]:
A = np.array([[2,-1,-1],[0,-1,0],[0,2,1]])
e = np.linalg.eig(A)
print(e[0])
print(e[1])

[ 2.  1. -1.]
[[ 1.          0.70710678  0.        ]
 [ 0.          0.          0.70710678]
 [ 0.          0.70710678 -0.70710678]]


In [ ]:
B = np.array([[-5,3,-6],[0,-2,0],[3,-3,4]])
e = np.linalg.eig(B)
print(e[0])
print(e[1])

[-2.  1. -2.]
[[-0.89442719  0.70710678  0.18257419]
 [ 0.          0.          0.91287093]
 [ 0.4472136  -0.70710678  0.36514837]]


In [ ]:
v0 = np.array([-2,0,2])
estado(B,v0,1)

(array([-0.70710678,  0.        ,  0.70710678]), 1.0000000000000002)