In [ ]:
import numpy as np
import scipy.linalg

def row_echelon(M):
    """ Return Row Echelon Form of matrix A """
    A = np.copy(M)
    if (issubclass(A.dtype.type, np.integer)):
        A = A.astype(float)
    #A = M.astype(float)
    # if matrix A has no columns or rows,
    # it is already in REF, so we return itself
    r, c = A.shape
    if r == 0 or c == 0:
        return A

    # we search for non-zero element in the first column
    for i in range(len(A)):
        if A[i,0] != 0:
            break
    else:
        # if all elements in the first column is zero,
        # we perform REF on matrix from second column
        B = row_echelon(A[:,1:])
        # and then add the first zero-column back
        return np.hstack([A[:,:1], B])

    # if non-zero element happens not in the first row,
    # we switch rows
    if i > 0:
        ith_row = A[i].copy()
        A[i] = A[0]
        A[0] = ith_row

    # we divide first row by first element in it
    A[0] = A[0] / A[0,0]
    # we subtract all subsequent rows with first row (it has 1 now as first element)
    # multiplied by the corresponding element in the first column
    A[1:] -= A[0] * A[1:,0:1]

    # we perform REF on matrix from second row, from second column
    B = row_echelon(A[1:,1:])

    # we add first row and first (zero) column, and return
    return np.vstack([A[:1], np.hstack([A[1:,:1], B]) ])


# EJ1


In [ ]:
a = 1
A =np.array([[2,1,0,0],[1,a,a,-1],[0,0,-a,1],[0,0,a,-1]])
print(A)
print("IM(f) = ", row_echelon(A.T))
print("NU(f) = ", row_echelon(A))
scipy.linalg.null_space(A)

[[ 2  1  0  0]
 [ 1  1  1 -1]
 [ 0  0 -1  1]
 [ 0  0  1 -1]]
IM(f) =  [[ 1.   0.5  0.   0. ]
 [ 0.   1.   0.   0. ]
 [ 0.   0.   1.  -1. ]
 [ 0.   0.   0.   0. ]]
NU(f) =  [[ 1.   0.5  0.   0. ]
 [ 0.   1.   2.  -2. ]
 [ 0.   0.   1.  -1. ]
 [ 0.   0.   0.   0. ]]


array([[ 0.00000000e+00],
       [-5.28614384e-17],
       [ 7.07106781e-01],
       [ 7.07106781e-01]])

In [ ]:
T=np.array([[1,1,1,-3],[1,-1,0,0],[1,-3,-1,-3]])
row_echelon(T)

array([[ 1. ,  1. ,  1. , -3. ],
       [ 0. ,  1. ,  0.5, -1.5],
       [ 0. ,  0. ,  0. ,  1. ]])

In [ ]:
S = np.array([[1,1,-2,0],[0,0,-1,1]])

In [ ]:
veo1 = np.c_[S.T,T[0]]

In [ ]:
row_echelon(veo1.T)

array([[ 1.,  1., -2.,  0.],
       [ 0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0.]])

In [ ]:
veo2 = np.c_[S.T,T[1]]
row_echelon(veo2.T)

array([[ 1.,  1., -2.,  0.],
       [ 0.,  1., -1., -0.],
       [ 0.,  0.,  1., -1.]])

In [ ]:
veo3 = np.c_[S.T,T[2]]
row_echelon(veo2.T)

array([[ 1.,  1., -2.,  0.],
       [ 0.,  1., -1., -0.],
       [ 0.,  0.,  1., -1.]])

In [ ]:
ST= np.c_[T.T,S[0]]
ST =np.c_[ST,S[1]]
row_echelon(ST.T) #S+T pertenece R4

array([[ 1. ,  1. ,  1. , -3. ],
       [ 0. ,  1. ,  0.5, -1.5],
       [ 0. ,  0. ,  1. , -1. ],
       [ 0. ,  0. ,  0. ,  1. ],
       [ 0. ,  0. ,  0. ,  0. ]])

In [ ]:
STNU = np.c_[ST,np.array([0,0,1,1])]
row_echelon(STNU.T)

array([[ 1. ,  1. ,  1. , -3. ],
       [ 0. ,  1. ,  0.5, -1.5],
       [ 0. ,  0. ,  1. , -1. ],
       [ 0. ,  0. ,  0. ,  1. ],
       [ 0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ]])

In [ ]:
g = np.array([[1,1,-2,0, 2,1,0,0],[0,0,-1,1, 0,1,0,0], [1,-1,0,0, 0,-1,1,-1],[1,-3,-1,-3,0,0,0,0]])

In [ ]:
print(row_echelon(g))

[[ 1.          1.         -2.          0.          2.          1.
   0.          0.        ]
 [ 0.          1.         -1.         -0.          1.          1.
  -0.5         0.5       ]
 [ 0.          0.          1.         -1.         -0.         -1.
  -0.         -0.        ]
 [ 0.          0.          0.          1.         -0.33333333 -0.
   0.33333333 -0.33333333]]


In [ ]:
a = 1
Af =np.array([[2,1,0,0],[1,a,a,-1],[0,0,-a,1],[0,0,a,-1]])
print(Af)
Ah = np.array([[1,-1,0],[0,0,1],[0,1,-2],[1,0,0]])
print(Ah)

[[ 2  1  0  0]
 [ 1  1  1 -1]
 [ 0  0 -1  1]
 [ 0  0  1 -1]]
[[ 1 -1  0]
 [ 0  0  1]
 [ 0  1 -2]
 [ 1  0  0]]


In [ ]:
AFAH= Af@Ah
AFAH


array([[ 2, -2,  1],
       [ 0,  0, -1],
       [ 1, -1,  2],
       [-1,  1, -2]])

In [ ]:
row_echelon(AFAH)

array([[ 1. , -1. ,  0.5],
       [ 0. ,  0. ,  1. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ]])

In [ ]:
scipy.linalg.null_space(AFAH)

array([[7.07106781e-01],
       [7.07106781e-01],
       [1.11022302e-16]])

# EJ2


* me falta ver que cond_2 -> inf tambien

In [ ]:
e = 0
A = np.array([[1,2,1],[2,3-e,2+e],[0,1+e,e]])
A

array([[1, 2, 1],
       [2, 3, 2],
       [0, 1, 0]])

In [ ]:
print("cond inf = ",np.linalg.cond(A,np.inf))
print("cond 2 = ",np.linalg.cond(A,2))

cond inf =  inf
cond 2 =  3.640099130599161e+16


In [ ]:
np.linalg.det(A)

0.0

In [ ]:
e = 10**(-3)
A = np.array([[1,2,1],[2,3-e,2+e],[0,1+e,e]])
A
np.linalg.inv(A)

array([[ 9.99001998e+02, -4.99000999e+02, -5.00999001e+02],
       [ 9.99000999e-01, -4.99500500e-01,  4.99500500e-01],
       [-1.00000000e+03,  5.00000000e+02,  5.00000000e+02]])

In [ ]:
e = 0
A = np.array([[1,2,1],[2,3-e,2+e],[0,1+e,e]])
A@np.array([1,0,-1])

array([0, 0, 0])

In [ ]:
L = np.array([[1,0,0],[2 ,1,0],[0 ,-1 ,1]])
U = np.array([[1,2,1],[0,-1-e,e],[0,0,2*e]])
print(L)
print(U)

[[ 1  0  0]
 [ 2  1  0]
 [ 0 -1  1]]
[[ 1  2  1]
 [ 0 -1  0]
 [ 0  0  0]]


In [ ]:
b = np.array([0,0.1,0.1])

In [ ]:
np.linalg.solve(A,b)

LinAlgError: ignored

In [ ]:
2.001-2

In [ ]:
y = np.array([0,0.1,0.2])
verdadero= np.array([-100,0,100])

In [ ]:
0.1/0.002

In [ ]:
-1.001*2


# EJ3


In [ ]:
def estado(A,v,k):
  for i in range(k):
    Av= A@v
    v = Av / np.linalg.norm(Av,2)
    r= (v.T@A@v)/(v.T@v)
  return(v,r)
  

In [ ]:
A = np.array([[-6,9,3],[0,8,-2],[0,-1,7]])
np.linalg.det(A)

-323.9999999999999

In [ ]:
e = np.linalg.eig(A)
print(e[0])
print(e[1])

[-6.  9.  6.]
[[ 1.          0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]
 [ 0.         -0.40824829  0.57735027]]


In [ ]:
A - (-6)*np.eye(3)

In [ ]:
B = np.array([[5,9,6],[-3,-7,-6],[0,0,-1]])
np.linalg.det(B)

7.999999999999998

In [ ]:
e = np.linalg.eig(B)
print(e[0])
print(e[1])

[ 2. -4. -1.]
[[ 0.9486833  -0.70710678  0.66666667]
 [-0.31622777  0.70710678 -0.66666667]
 [ 0.          0.          0.33333333]]


In [ ]:
B - (-4)*np.eye(3)

array([[ 9.,  9.,  6.],
       [-3., -3., -6.],
       [ 0.,  0.,  3.]])

In [ ]:
alpha = 1
v0 = np.array([-1,alpha,-2])

estado(B,v0,1000)

(array([ 0.70710678, -0.70710678,  0.        ]), -3.9999999999999982)

In [ ]:
b0 = np.array([2,1,1])
estado(A,b0,100)

(array([ 0.43114846,  0.81606008, -0.38491162]), 8.86045540720657)