# Métodos iterativos

In [1]:
import numpy as np

**Ejercicio 1 de la práctica:**

a. Escribir un programa que implemente el método de Jacobi en forma matricial y
otro que implemente el método de Gauss-Seidel para la
resolución de un sistema lineal $Ax = b$ con las siguientes
condiciones:
- que finalice si el método se estaciona,
- que finalice con una advertencia si se excede cierto tope de iteraciones,

Sugerencia: investigar los comandos `np.tril`, `np.triu` y `np.diag`.

b. Utilizar el programa para resolver el sistema
$$ A={\begin{bmatrix}16&3\\7&-11\\\end{bmatrix}}, \quad {\displaystyle b={\begin{bmatrix}11\\13\end{bmatrix}}}.$$

c. Modificar los programas utilizando `np.linalg.solve` en vez del cálculo de inversas.

In [2]:
def jacobiMat(A, b, x0, s):
    n = np.shape(A)[0]
    
    x = x0
    M = np.diag(np.diag(A))
    N = A - M
    for k in range(s):
        x = -(np.linalg.inv(M) @ N) @ x + np.linalg.inv(M) @ b
        print(x)
    return(x)

2. Verificar que el método de Jacobi aplicado a 
$$
A = \begin{pmatrix} 
1 & 2 & -2 \\
1 & 1 & 1 \\
2 & 2 & 1
\end{pmatrix}, \quad b = \begin{pmatrix} 3 \\ 6 \\ 11 \end{pmatrix}
$$
converge en 3 pasos. 

¿Converge el método de Gauss-Siedel para este ejemplo?

In [8]:
A = np.array([[1,2,-2], [1, 1, 1], [2, 2, 1]]).astype(float)
b = np.array([3, 6, 11]).astype(float)
print(A)
print(b)
jacobiMat(A,b,np.zeros(3),3)

[[ 1.  2. -2.]
 [ 1.  1.  1.]
 [ 2.  2.  1.]]
[ 3.  6. 11.]
[ 3.  6. 11.]
[13. -8. -7.]
[5. 0. 1.]


array([5., 0., 1.])

3. Determinar mediante una simulación si el método de Jacobi converge para 
$$
A = \begin{pmatrix}
1 & 2 & 1 \\
4 & 2 & 2 \\
0 & 0 & 0.5 
\end{pmatrix},   \quad b = \begin{pmatrix} 7 \\ 20 \\ 2 \end{pmatrix}$$
y vectores $x_0$ aleatorios.

Encontrar analíticamente la solución del sistema, y un vector $x_0$ para el cual el método converja, que no sea solución del sistema.



In [4]:
A = np.array([[1,2,1], [4, 2, 2], [0, 0, 0.5]]).astype(float)
b = np.array([7, 20, 2]).astype(float)
print(A)
print(b)

[[1.  2.  1. ]
 [4.  2.  2. ]
 [0.  0.  0.5]]
[ 7. 20.  2.]


2. Escribir un programa que reciba una matriz $A$, un vector $b$, un vector inicial $x0$ y un natural $s$ y realice $s$ iteraciones del método de Jacobi para resolver el sistema $Ax = b$ utilizando las ecuaciones
$$x_i^{(k)}=\frac{b_i-\sum_{j \neq i} a_{ij} x_j^{(k-1)}}{a_{ii}},\quad i=1,2,\dots ,n.$$

Verificar el programa con el ejemplo anterior.

In [5]:
def jacobiEq(A, b, x0, s):
    n = np.shape(A)[0]
    
    xOld = x0
    xNew = np.zeros(n)
    for k in range(s):
        for i in range(n):
            xNew[i] = (b[i] - (sum(A[i,:]*xOld) - A[i,i] * xOld[i])) / A[i,i]
        xOld = xNew.copy()      ## USAR SIEMPRE COPY PARA COPIAR VECTORES Y MATRICES
    return(xNew)
    

4. Escribir un programa que reciba una matriz $A$, un vector $b$, un vector inicial $x0$ y un natural $s$ y realice $s$ iteraciones del método de Gauss-Seidel para resolver el sistema $Ax = b$ utilizando las ecuaciones
$$
{\displaystyle x_{i}^{(k)}={\frac {1}{a_{ii}}}\left(b_{i}-\sum _{j=1}^{i-1}a_{ij}x_{j}^{(k)}-\sum _{j=i+1}^{n}a_{ij}x_{j}^{(k-1)}\right),\quad i=1,2,\dots ,n.}
$$


## 5. Método SOR

(Ejercicio 11 de la práctica.)

a. Verificar que el sistema $Ax = b$ es equivalente al sistema 
$$(D+\omega L) x=((1-\omega)D - \omega U) x +\omega b,$$
para $\omega \neq 0$. 

b. Escribir el método SOR en la forma $x^{(k+1)} = B_{sor} x^{(k)} + c$ y verificar que la matriz del método es 
$$B(\omega)=(D+\omega L)^{-1}((1-\omega)D - \omega U).$$ 

Calcular el determinante de $B(\omega)$ y probar que si el método converge, debe ser $w \in (0, 2)$.

c. Para 
$$ A={\begin{bmatrix}16&3\\7&-11\\\end{bmatrix}}, \quad {\displaystyle b={\begin{bmatrix}11\\13\end{bmatrix}}}.$$
hallar mediante una simulación los valores para los que el método converge. Y estimar el valor para el cuál la convergencia es más rápida.