In [ ]:
import numpy as np
import scipy.linalg
import math
def row_echelon(M):
    """ Return Row Echelon Form of matrix A """
    A = np.copy(M)
    if (issubclass(A.dtype.type, np.integer)):
        A = A.astype(float)
    #A = M.astype(float)
    # if matrix A has no columns or rows,
    # it is already in REF, so we return itself
    r, c = A.shape
    if r == 0 or c == 0:
        return A

    # we search for non-zero element in the first column
    for i in range(len(A)):
        if A[i,0] != 0:
            break
    else:
        # if all elements in the first column is zero,
        # we perform REF on matrix from second column
        B = row_echelon(A[:,1:])
        # and then add the first zero-column back
        return np.hstack([A[:,:1], B])

    # if non-zero element happens not in the first row,
    # we switch rows
    if i > 0:
        ith_row = A[i].copy()
        A[i] = A[0]
        A[0] = ith_row

    # we divide first row by first element in it
    A[0] = A[0] / A[0,0]
    # we subtract all subsequent rows with first row (it has 1 now as first element)
    # multiplied by the corresponding element in the first column
    A[1:] -= A[0] * A[1:,0:1]

    # we perform REF on matrix from second row, from second column
    B = row_echelon(A[1:,1:])

    # we add first row and first (zero) column, and return
    return np.vstack([A[:1], np.hstack([A[1:,:1], B]) ])

#Transformaciones Lineales



#Cond

In [ ]:
B = np.array([[0,0,-1],[2,1,0],[0,-4,2]])
print(B)
print('Norma 1 = ', np.linalg.norm(B,1))
print('Norma 2 = ', np.linalg.norm(B,2))
print('Norma inf = ', np.linalg.norm(B,np.inf))

[[ 0  0 -1]
 [ 2  1  0]
 [ 0 -4  2]]
Norma 1 =  5.0
Norma 2 =  4.602892749074813
Norma inf =  6.0


In [ ]:
print(np.linalg.eig(B.T@B)[0])
np.sqrt(np.linalg.eig(B.T@B)[0][0])

[21.18662166  4.07143497  0.74194337]


4.602892749074812

* Norma 1 = maximo de la suma de los modulos de los elementos de las columnas
* Norma 2 = sqrt(max autovalor de $B^tB$)
* Norma $∞$= maximo de la suma de los modulos de los elementos de las filas



In [ ]:
A = np.array([[3,0,0],[0,5/4,3/4],[0,3/4,5/4]])
Ainv = np.linalg.inv(A)
print(A)
print(np.linalg.norm(A,np.inf))
print(Ainv)
print(np.linalg.norm(Ainv,np.inf))
print('cond_inf = ' ,np.linalg.norm(A,np.inf)*np.linalg.norm(Ainv,np.inf))

[[3.   0.   0.  ]
 [0.   1.25 0.75]
 [0.   0.75 1.25]]
3.0
[[ 0.33333333  0.          0.        ]
 [ 0.          1.25       -0.75      ]
 [ 0.         -0.75        1.25      ]]
2.0
cond_inf =  6.0


Para calcular $cond_p$ tenemos que hacer $||A||_p$ $*$ $||A^{-1}||_p$  si A es una matriz cuadrada y regular, si NO es invertible $cond(A) = +∞$

Else tenemos que $cond_p = \frac{||A||_p}{||A_s - A||_p},$ donde $A_s = A$ con el valor de $α$ propuesto

* en numpy tenemos np.linalg.cond(A, p)

In [ ]:
P = np.array([[3,1,2],[1,2,4],[2,1,1]])
print(np.linalg.norm(P,2)*np.linalg.norm(np.linalg.inv(P),2))
np.linalg.cond(P,1)

16.22927858185058


21.0

In [ ]:
e = 0.01
A= np.array([[1,1,1],[1,0,e],[1,0,e**2]])
B = np.array([[1,0,1+e],[2,3,4],[1-e,0,1]])
print(np.linalg.cond(A,np.inf))
print(np.linalg.cond(B,np.inf))

606.0606060606054
180900.00000022075


In [ ]:
n = 10**4
A = np.array([[1, n, 5*n],[1, 3*n, 3*n],[1, n, 2*n]])
B = np.array([(2*n)/3, (2*n)/3, n/3])
x = np.array([0,1/9,1/9])

In [ ]:
X = np.linalg.solve(A,B)
X

array([2.27373675e-13, 1.11111111e-01, 1.11111111e-01])

In [ ]:
np.linalg.norm(X-x,np.inf)/np.linalg.norm(x,np.inf)

2.0463630789890885e-12

In [ ]:
v1 = np.array([1,1,1,1])
v2 = np.array([1,2,1,0])
v3 = np.array([0,0,1,3])

u1 = v1/np.linalg.norm(v1,2)

u2 = v2 - (np.dot(v2,u1) / np.dot(u1,u1))*u1
u2 = u2/np.linalg.norm(u2)

#u3 = v3 - ((np.dot(v3,u2) / np.dot(u2,u2))*u2) - ((np.dot(v3,u1) / np.dot(u1,u1))*u1)

print(u1,u2)

[0.5 0.5 0.5 0.5] [ 0.          0.70710678  0.         -0.70710678]


Para ortonormalizar bases debo usar Gram-Schimidt
* Partiendo de una **base** de vectores $v_k$ de un espacio $V = (v_1,v_2,v_3,...,v_k)$
* $u_k = v_k - \sum^{k-1}_{j=1} \frac{<v_k,u_j>}{<u_j,u_j>}u_j$
* $u_k = \frac{u_k}{||u_k||}$ es decir, normalizo $u_k$


La idea atras de esto es ir restando las proyecciones de $v_k$ en todos los $u_n$ anteriores $u_k$

In [ ]:
S = np.c_[u1,u2]
print(S)
P = S@np.linalg.inv(S.T@S)@S.T
P

[[ 0.5         0.        ]
 [ 0.5         0.70710678]
 [ 0.5         0.        ]
 [ 0.5        -0.70710678]]


array([[ 0.25,  0.25,  0.25,  0.25],
       [ 0.25,  0.75,  0.25, -0.25],
       [ 0.25,  0.25,  0.25,  0.25],
       [ 0.25, -0.25,  0.25,  0.75]])

Para hacer la matriz de proyeccion $P$ debo usar:
* $P = U(U^tU)^{-1}U^t$

La formula de la proyeccion de $v$ en $P$ es:
* $w = Pv$

In [ ]:
A = np.array([[1,-1,0,1],[-1,0,-2,0],[0,1,1,-1],[3,1,2,-1]])
A

array([[ 1, -1,  0,  1],
       [-1,  0, -2,  0],
       [ 0,  1,  1, -1],
       [ 3,  1,  2, -1]])

In [ ]:
np.linalg.cond(A)

1.4706498512606065e+18

In [ ]:
L = np.array([[1,0,0,0],[-1,1,0,0],[0,-1,1,0],[3,-4,6,1]])
U = np.array([[1,-1,0,1],[0,-1,-2,1],[0,0,-1,0],[0,0,0,0]])

print(A)
L@U

[[ 1 -1  0  1]
 [-1  0 -2  0]
 [ 0  1  1 -1]
 [ 3  1  2 -1]]


array([[ 1, -1,  0,  1],
       [-1,  0, -2,  0],
       [ 0,  1,  1, -1],
       [ 3,  1,  2, -1]])

In [ ]:
V = row_echelon(A)
V

array([[ 1., -1.,  0.,  1.],
       [ 0.,  1.,  2., -1.],
       [ 0.,  0.,  1., -0.],
       [ 0.,  0.,  0.,  0.]])

In [ ]:
v1 = np.array([1,-1,0,1])
v2 = np.array([0,1,2,-1])
v3 = np.array([0,0,1,0])

In [ ]:
u1 = v1/ np.linalg.norm(v1)
u1

array([ 0.57735027, -0.57735027,  0.        ,  0.57735027])

In [ ]:
u2 = v2 - (np.dot(v2,u1) / np.dot(u1,u1))*u1
u2 = u2 / np.linalg.norm(u2)
u2

array([ 0.3086067 ,  0.15430335,  0.9258201 , -0.15430335])

In [ ]:
u3 = v3 - (np.dot(v3,u2)/np.dot(u2,u2))*u2 - (np.dot(v3,u1)/np.dot(u1,u1))*u1
u3 = u3 / np.linalg.norm(u3)
u3

array([-0.75592895, -0.37796447,  0.37796447,  0.37796447])

In [ ]:
U = np.c_[u1,u2,u3]
U

array([[ 0.57735027,  0.3086067 , -0.75592895],
       [-0.57735027,  0.15430335, -0.37796447],
       [ 0.        ,  0.9258201 ,  0.37796447],
       [ 0.57735027, -0.15430335,  0.37796447]])

In [ ]:
P = U@np.linalg.inv(U.T@U)@U.T
print(P)

[[ 1.00000000e+00 -2.89333048e-17 -2.78943369e-17  2.89333048e-17]
 [-5.19483958e-19  5.00000000e-01 -1.39471684e-17 -5.00000000e-01]
 [-5.49916673e-17 -1.32889232e-17  1.00000000e+00  1.32889232e-17]
 [ 5.19483958e-19 -5.00000000e-01  1.39471684e-17  5.00000000e-01]]


In [ ]:
print('en nu(g) = ', P@np.array([0,1,0,1]))
print('en nu(g)ortogonal = ', P@np.array([0,1,0,-1]))

en nu(g) =  [0. 0. 0. 0.]
en nu(g)ortogonal =  [-5.78666096e-17  1.00000000e+00 -2.65778464e-17 -1.00000000e+00]
